# Generated by Django 2.1.2 on 2018-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20181016_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phoneNo',
            field=models.BigIntegerField(),
        ),
    ]
