# Generated by Django 2.1.2 on 2018-10-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='person',
            new_name='personportfolio',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='person',
            new_name='personskills',
        ),
    ]
