# Generated by Django 2.1.2 on 2018-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20181016_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='personportfolio',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='personskills',
        ),
        migrations.AddField(
            model_name='person',
            name='portfolios',
            field=models.ManyToManyField(to='about.Portfolio'),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='about.Skills'),
        ),
    ]
